version: '3.7'

services:

  postgres-targsoft-app:
    image: postgres:11.4-alpine
    hostname: postgres-targsoft-app
    env_file:
      - ../.env
    shm_size: '100'
    command: >
      postgres
      -c shared_preload_libraries='pg_stat_statements'
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=10MB
      -c statement_timeout=180000
    tmpfs:
      - /tmp:size=10M
    volumes:
      - db-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    ports:
      - 5457:5432
    networks:
      - targsoft-network

  targsoft-app:
    image: targsoft-app:0.0.1
    hostname: targsoft-app
    env_file:
      - ../.env
    ports:
      - 8054:8080
    networks:
      - targsoft-network

volumes:
  db-data:
    driver: local

networks:
  targsoft-network:
    driver: bridge